version: '3'

services:
  database:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - loteria-db-data:/data/db
    env_file:
      - ./.env
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ./.env
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #   ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  loteria-db-data:
