version: '3'

services:
  database:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  postgres:
  pgadmin:
